faa = faa version 21
democonfigclient.message=hello spring io
spring:
  application:
  name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CNlishengzhe/surprised
          search-paths: sc-config
          username:
          password:
        default-label: master

server:
  port: 8888
